/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.kmnos.mekup.loginscreen;

import javax.swing.JOptionPane;

/**
 *
 * @author tailaneb
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        pnlTabs.remove(pnlPerfil);
        pnlTabs.remove(pnlAgenda);
        pnlTabs.remove(pnlServicos);
        pnlTabs.remove(pnlPacotes);
        pnlTabs.remove(pnlRanking);
    }
   
    private int cont = 0;

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMenu = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblEmailUsuario = new javax.swing.JLabel();
        btnAgenda = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        btnPacotes = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        pnlTabs = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        Mapa = new javax.swing.JPanel();
        btnBuscar1 = new javax.swing.JButton();
        txtBuscar1 = new javax.swing.JTextField();
        pnlGoogleMaps1 = new javax.swing.JPanel();
        pnlPerfil = new javax.swing.JPanel();
        btnFecharPerfil = new javax.swing.JButton();
        lblImagemPerfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblIconRanking = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnlAgenda = new javax.swing.JPanel();
        btnFecharAgenda = new javax.swing.JButton();
        pnlServicos = new javax.swing.JPanel();
        btnFecharServicos = new javax.swing.JButton();
        pnlPacotes = new javax.swing.JPanel();
        btnFecharPacotes = new javax.swing.JButton();
        pnlRanking = new javax.swing.JPanel();
        btnFecharRanking = new javax.swing.JButton();
        pnlChat = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        menSistema = new javax.swing.JMenuBar();
        menMenuPrincipal = new javax.swing.JMenu();
        mniDeslogar = new javax.swing.JMenuItem();
        mniFechar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenu.setBackground(new java.awt.Color(204, 255, 204));

        btnPerfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPerfil.setText("Perfil");
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeUsuario.setText("jLabel12");

        lblEmailUsuario.setText("jLabel12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeUsuario)
                            .addComponent(lblEmailUsuario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNomeUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblEmailUsuario)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnAgenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgenda.setText("Agenda");
        btnAgenda.setBorderPainted(false);
        btnAgenda.setContentAreaFilled(false);
        btnAgenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });

        btnServicos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnServicos.setText("Serviços");
        btnServicos.setBorderPainted(false);
        btnServicos.setContentAreaFilled(false);
        btnServicos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });

        btnPacotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPacotes.setText("Pacotes");
        btnPacotes.setBorderPainted(false);
        btnPacotes.setContentAreaFilled(false);
        btnPacotes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacotesActionPerformed(evt);
            }
        });

        btnRanking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRanking.setText("Ranking");
        btnRanking.setBorderPainted(false);
        btnRanking.setContentAreaFilled(false);
        btnRanking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPacotes, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnPerfil)
                .addGap(18, 18, 18)
                .addComponent(btnAgenda)
                .addGap(18, 18, 18)
                .addComponent(btnServicos)
                .addGap(18, 18, 18)
                .addComponent(btnPacotes)
                .addGap(18, 18, 18)
                .addComponent(btnRanking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTabs.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pnlTabsComponentAdded(evt);
            }
        });

        pnlHome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pnlHomeComponentAdded(evt);
            }
        });
        pnlHome.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlHomeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pnlHome.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pnlHomePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );

        pnlTabs.addTab("HOME", pnlHome);

        Mapa.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MapaComponentAdded(evt);
            }
        });
        Mapa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MapaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Mapa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MapaPropertyChange(evt);
            }
        });

        btnBuscar1.setText("Buscar");

        pnlGoogleMaps1.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout pnlGoogleMaps1Layout = new javax.swing.GroupLayout(pnlGoogleMaps1);
        pnlGoogleMaps1.setLayout(pnlGoogleMaps1Layout);
        pnlGoogleMaps1Layout.setHorizontalGroup(
            pnlGoogleMaps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        pnlGoogleMaps1Layout.setVerticalGroup(
            pnlGoogleMaps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MapaLayout = new javax.swing.GroupLayout(Mapa);
        Mapa.setLayout(MapaLayout);
        MapaLayout.setHorizontalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGoogleMaps1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MapaLayout.createSequentialGroup()
                        .addComponent(txtBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addGap(64, 64, 64)
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MapaLayout.setVerticalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(pnlGoogleMaps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Busca", Mapa);

        btnFecharPerfil.setText("Fechar");
        btnFecharPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPerfilActionPerformed(evt);
            }
        });

        lblImagemPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpg"))); // NOI18N
        lblImagemPerfil.setText("jLabel1");

        jLabel2.setText("Mudar Imagem: ");

        jLabel3.setText("Excluir Imagem:");

        jButton1.setText("Excluir");

        jLabel4.setText("Nome:");

        jLabel5.setText("Usuário:");

        jLabel6.setText("Email:");

        jLabel7.setText("Telefone:");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField1");

        jTextField4.setText("jTextField1");

        jLabel8.setText("Endereço:");

        jTextField5.setText("jTextField1");

        jLabel11.setText("Ranking Geral:");

        lblIconRanking.setText("jLabel12");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/Edit_File-50.png"))); // NOI18N

        jCheckBox1.setText("Cartão de Crédito");

        jCheckBox2.setText("Cartão de Débito");

        jCheckBox3.setText("Cheque");

        jCheckBox4.setText("Dinheiro");

        jLabel9.setText("Forma de Pagamento:");

        jLabel10.setText("Atendimento domiciliar?");

        jCheckBox5.setText("Sim");

        jCheckBox6.setText("Não");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox3)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox6))
                            .addComponent(jLabel10))
                        .addGap(113, 113, 113))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addContainerGap())
        );

        jButton3.setText("jButton2");

        jButton4.setText("jButton2");

        jButton5.setText("jButton2");

        javax.swing.GroupLayout pnlPerfilLayout = new javax.swing.GroupLayout(pnlPerfil);
        pnlPerfil.setLayout(pnlPerfilLayout);
        pnlPerfilLayout.setHorizontalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFecharPerfil)
                .addContainerGap())
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(241, 241, 241))
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPerfilLayout.createSequentialGroup()
                                .addComponent(lblImagemPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(154, 154, 154)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblIconRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1)))
                            .addGroup(pnlPerfilLayout.createSequentialGroup()
                                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)
                                    .addComponent(jButton5))))
                        .addContainerGap())))
        );
        pnlPerfilLayout.setVerticalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFecharPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagemPerfil)
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIconRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlPerfilLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel11))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(69, 69, 69)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(62, 62, 62)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(23, 23, 23)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Perfil", pnlPerfil);

        btnFecharAgenda.setText("Fechar");
        btnFecharAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgendaLayout = new javax.swing.GroupLayout(pnlAgenda);
        pnlAgenda.setLayout(pnlAgendaLayout);
        pnlAgendaLayout.setHorizontalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                .addContainerGap(610, Short.MAX_VALUE)
                .addComponent(btnFecharAgenda)
                .addContainerGap())
        );
        pnlAgendaLayout.setVerticalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFecharAgenda)
                .addContainerGap(703, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Agenda", pnlAgenda);

        btnFecharServicos.setText("Fechar");
        btnFecharServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharServicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServicosLayout = new javax.swing.GroupLayout(pnlServicos);
        pnlServicos.setLayout(pnlServicosLayout);
        pnlServicosLayout.setHorizontalGroup(
            pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addContainerGap(610, Short.MAX_VALUE)
                .addComponent(btnFecharServicos)
                .addContainerGap())
        );
        pnlServicosLayout.setVerticalGroup(
            pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFecharServicos)
                .addContainerGap(703, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Serviços", pnlServicos);

        btnFecharPacotes.setText("Fechar");
        btnFecharPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPacotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPacotesLayout = new javax.swing.GroupLayout(pnlPacotes);
        pnlPacotes.setLayout(pnlPacotesLayout);
        pnlPacotesLayout.setHorizontalGroup(
            pnlPacotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPacotesLayout.createSequentialGroup()
                .addContainerGap(610, Short.MAX_VALUE)
                .addComponent(btnFecharPacotes)
                .addContainerGap())
        );
        pnlPacotesLayout.setVerticalGroup(
            pnlPacotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFecharPacotes)
                .addContainerGap(703, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Pacotes", pnlPacotes);

        btnFecharRanking.setText("Fechar");
        btnFecharRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRankingLayout = new javax.swing.GroupLayout(pnlRanking);
        pnlRanking.setLayout(pnlRankingLayout);
        pnlRankingLayout.setHorizontalGroup(
            pnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRankingLayout.createSequentialGroup()
                .addContainerGap(610, Short.MAX_VALUE)
                .addComponent(btnFecharRanking)
                .addContainerGap())
        );
        pnlRankingLayout.setVerticalGroup(
            pnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFecharRanking)
                .addContainerGap(703, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Ranking", pnlRanking);

        jLabel12.setText("CHAT");

        javax.swing.GroupLayout pnlChatLayout = new javax.swing.GroupLayout(pnlChat);
        pnlChat.setLayout(pnlChatLayout);
        pnlChatLayout.setHorizontalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        pnlChatLayout.setVerticalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChatLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menMenuPrincipal.setText("Sistema");
        menMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMenuPrincipalActionPerformed(evt);
            }
        });

        mniDeslogar.setText("Deslogar");
        mniDeslogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniDeslogarMouseClicked(evt);
            }
        });
        mniDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeslogarActionPerformed(evt);
            }
        });
        menMenuPrincipal.add(mniDeslogar);

        mniFechar.setText("Fechar");
        mniFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFecharActionPerformed(evt);
            }
        });
        menMenuPrincipal.add(mniFechar);

        menSistema.add(menMenuPrincipal);

        jMenu2.setText("Edit");
        menSistema.add(jMenu2);

        setJMenuBar(menSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTabs)
                    .addComponent(pnlChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
                       
        try {
            cont++;
            
            if (cont == 1) {
                pnlTabs.add("Perfil",pnlPerfil);
                pnlTabs.setSelectedComponent(pnlPerfil);
                cont=0;
            } 
            
        } catch (java.lang.IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Error ao tentantar acessar o painel Perfil \n " + ex);
            
        }


    }//GEN-LAST:event_btnPerfilActionPerformed

    private void mniDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeslogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDeslogarActionPerformed

    private void btnFecharRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharRankingActionPerformed
        // TODO add your handling code here:
        int i = pnlTabs.indexOfComponent(pnlRanking);
        if (i != -1) {
            pnlTabs.remove(i);
        }
    }//GEN-LAST:event_btnFecharRankingActionPerformed

    private void btnFecharPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPacotesActionPerformed
        // TODO add your handling code here:
        int i = pnlTabs.indexOfComponent(pnlPacotes);
        if (i != -1) {
            pnlTabs.remove(i);
        }
    }//GEN-LAST:event_btnFecharPacotesActionPerformed

    private void btnFecharServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharServicosActionPerformed
        // TODO add your handling code here:
        int i = pnlTabs.indexOfComponent(pnlServicos);
        if (i != -1) {
            pnlTabs.remove(i);
        }
    }//GEN-LAST:event_btnFecharServicosActionPerformed

    private void btnFecharAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharAgendaActionPerformed
        // TODO add your handling code here:
        int i = pnlTabs.indexOfComponent(pnlAgenda);
        if (i != -1) {
            pnlTabs.remove(i);
        }
    }//GEN-LAST:event_btnFecharAgendaActionPerformed

    private void btnFecharPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPerfilActionPerformed
        // TODO add your handling code here:
        int i = pnlTabs.indexOfComponent(pnlPerfil);
        if (i != -1) {
            pnlTabs.remove(i);
        }
    }//GEN-LAST:event_btnFecharPerfilActionPerformed

    private void pnlHomePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pnlHomePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHomePropertyChange

    private void pnlHomeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlHomeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHomeAncestorAdded

    private void pnlHomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlHomeComponentAdded
        
    }//GEN-LAST:event_pnlHomeComponentAdded

    private void pnlTabsComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlTabsComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnlTabsComponentAdded

    private void mniFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniFecharActionPerformed

    private void mniDeslogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniDeslogarMouseClicked

        
        
    }//GEN-LAST:event_mniDeslogarMouseClicked

    private void menMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMenuPrincipalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menMenuPrincipalActionPerformed

    private void MapaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MapaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MapaComponentAdded

    private void MapaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MapaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MapaAncestorAdded

    private void MapaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MapaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MapaPropertyChange

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        // TODO add your handling code here:
        try {
            cont++;
            
            if (cont == 1) {
                pnlTabs.add("Agenda",pnlAgenda);
                pnlTabs.setSelectedComponent(pnlAgenda);
                cont=0;
            } 
            
        } catch (java.lang.IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Error ao tentantar acessar o painel Agenda \n " + ex);
            
        }

    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
        // TODO add your handling code here:
        try {
            cont++;
            
            if (cont == 1) {
                pnlTabs.add("Serviços",pnlServicos);
                pnlTabs.setSelectedComponent(pnlServicos);
                cont=0;
            } 
            
        } catch (java.lang.IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Error ao tentantar acessar o painel Serviços \n " + ex);
            
        }
        
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacotesActionPerformed
        // TODO add your handling code here:
       try {
            cont++;
            
            if (cont == 1) {
                pnlTabs.add("Pacotes",pnlPacotes);
                pnlTabs.setSelectedComponent(pnlPacotes);
                cont=0;
            } 
            
        } catch (java.lang.IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Error ao tentantar acessar o painel Pacotes \n " + ex);
            
        }
    }//GEN-LAST:event_btnPacotesActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        try {
            cont++;
            
            if (cont == 1) {
                pnlTabs.add("Ranking",pnlRanking);
                pnlTabs.setSelectedComponent(pnlRanking);
                cont=0;
            } 
            
        } catch (java.lang.IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Error ao tentantar acessar o painel Ranking \n " + ex);
            
        }
    }//GEN-LAST:event_btnRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mapa;
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnFecharAgenda;
    private javax.swing.JButton btnFecharPacotes;
    private javax.swing.JButton btnFecharPerfil;
    private javax.swing.JButton btnFecharRanking;
    private javax.swing.JButton btnFecharServicos;
    private javax.swing.JButton btnPacotes;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnServicos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblEmailUsuario;
    private javax.swing.JLabel lblIconRanking;
    private javax.swing.JLabel lblImagemPerfil;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JMenu menMenuPrincipal;
    private javax.swing.JMenuBar menSistema;
    private javax.swing.JMenuItem mniDeslogar;
    private javax.swing.JMenuItem mniFechar;
    private javax.swing.JPanel pnlAgenda;
    private javax.swing.JPanel pnlChat;
    private javax.swing.JPanel pnlGoogleMaps1;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPacotes;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JPanel pnlRanking;
    private javax.swing.JPanel pnlServicos;
    private javax.swing.JTabbedPane pnlTabs;
    private javax.swing.JTextField txtBuscar1;
    // End of variables declaration//GEN-END:variables
}
